// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8UTDoWpsXtvD2FPkpIHZ3teN_kxrooYc',
    appId: '1:935098587257:web:17a2987b26bb9f6e00dca8',
    messagingSenderId: '935098587257',
    projectId: 'cepu-app-237cd',
    authDomain: 'cepu-app-237cd.firebaseapp.com',
    storageBucket: 'cepu-app-237cd.firebasestorage.app',
    measurementId: 'G-ZRPK9PXKMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlh6UImh6xH6K684iBYzL4mdo60_WbM34',
    appId: '1:935098587257:android:7a5f611dc168a9a800dca8',
    messagingSenderId: '935098587257',
    projectId: 'cepu-app-237cd',
    storageBucket: 'cepu-app-237cd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8UTDoWpsXtvD2FPkpIHZ3teN_kxrooYc',
    appId: '1:935098587257:web:0d206c649cb5e3c500dca8',
    messagingSenderId: '935098587257',
    projectId: 'cepu-app-237cd',
    authDomain: 'cepu-app-237cd.firebaseapp.com',
    storageBucket: 'cepu-app-237cd.firebasestorage.app',
    measurementId: 'G-1CZ3WPBN2C',
  );
}
