// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuwy1TfsieDScaCCxnP7LVLUD7tqmvPSk',
    appId: '1:979704107663:web:d66c47246238ad4d1956fa',
    messagingSenderId: '979704107663',
    projectId: 'hobi-app-47e77',
    authDomain: 'hobi-app-47e77.firebaseapp.com',
    storageBucket: 'hobi-app-47e77.firebasestorage.app',
    measurementId: 'G-4PJDKY984P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9JYRhadqPSLgeybm2o-LY8v14uxVAk6k',
    appId: '1:979704107663:android:7f9f009a4131a9b01956fa',
    messagingSenderId: '979704107663',
    projectId: 'hobi-app-47e77',
    storageBucket: 'hobi-app-47e77.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuwy1TfsieDScaCCxnP7LVLUD7tqmvPSk',
    appId: '1:979704107663:web:ff3d8b5efd2539ba1956fa',
    messagingSenderId: '979704107663',
    projectId: 'hobi-app-47e77',
    authDomain: 'hobi-app-47e77.firebaseapp.com',
    storageBucket: 'hobi-app-47e77.firebasestorage.app',
    measurementId: 'G-RZCK0RJ58Y',
  );
}
